#!/usr/bin/env python

def synthetize(bld):
    bld(
        target = "blink",
        source = ["main.v"],
        ucf = "papilio.ucf",
        device = "xc3s500e-4fg320"
    )

def simulate(bld):
    bld(
        target = "blink_bench",
        source = ["main.v", "blinkTest.v"]
    )
